package org.tton.hrm.domain;

import java.io.Serializable;

 /**
 * ClassName: Dept <br/>
 * Description: TODO <br/>
 * Date: 2018年3月23日 下午10:47:16 <br/>
 * <br/>
 * 
 * @author hanyouchuan(邮箱)
 * 
 * 修改记录
 * @version 产品版本信息 yyyy-mm-dd 姓名(邮箱) 修改信息<br/>
 * 
 */
public class Dept implements Serializable {
    private static final long serialVersionUID = 7830444319491515760L;

    public Dept() {
        super();
    }

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column dept_inf.ID
     * 
     * @mbggenerated Wed Jan 17 19:25:19 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column dept_inf.NAME
     * 
     * @mbggenerated Wed Jan 17 19:25:19 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column dept_inf.REMARK
     * 
     * @mbggenerated Wed Jan 17 19:25:19 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column dept_inf.ID
     * 
     * @return the value of dept_inf.ID
     * 
     * @mbggenerated Wed Jan 17 19:25:19 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column dept_inf.ID
     * 
     * @param id
     *            the value for dept_inf.ID
     * 
     * @mbggenerated Wed Jan 17 19:25:19 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column dept_inf.NAME
     * 
     * @return the value of dept_inf.NAME
     * 
     * @mbggenerated Wed Jan 17 19:25:19 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column dept_inf.NAME
     * 
     * @param name
     *            the value for dept_inf.NAME
     * 
     * @mbggenerated Wed Jan 17 19:25:19 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column dept_inf.REMARK
     * 
     * @return the value of dept_inf.REMARK
     * 
     * @mbggenerated Wed Jan 17 19:25:19 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column dept_inf.REMARK
     * 
     * @param remark
     *            the value for dept_inf.REMARK
     * 
     * @mbggenerated Wed Jan 17 19:25:19 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    @Override
    public String toString() {
        return "Dept [id=" + id + ", name=" + name + ", remark=" + remark + "]";
    }

}