package org.tton.hrm.domain;

import java.io.Serializable;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

 /**
 * ClassName: Employee <br/>
 * Description: TODO <br/>
 * Date: 2018年3月23日 下午10:47:27 <br/>
 * <br/>
 * 
 * @author hanyouchuan(邮箱)
 * 
 * 修改记录
 * @version 产品版本信息 yyyy-mm-dd 姓名(邮箱) 修改信息<br/>
 * 
 */
public class Employee implements Serializable{
 
    private static final long serialVersionUID = -815298619142820393L;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column employee_inf.id
     * 
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column employee_inf.dept_id
     * 
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    private Dept dept;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column employee_inf.job_id
     * 
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    private Job job;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column employee_inf.NAME
     * 
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column employee_inf.card_id
     * 
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    private String cardId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column employee_inf.address
     * 
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column employee_inf.post_code
     * 
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    private String postCode;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column employee_inf.tel
     * 
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column employee_inf.phone
     * 
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column employee_inf.qq_num
     * 
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    private String qqNum;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column employee_inf.email
     * 
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column employee_inf.sex
     * 
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column employee_inf.party
     * 
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    private String party;

    @DateTimeFormat(pattern="yyyy-MM-dd")
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column employee_inf.race
     * 
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    private String race;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column employee_inf.education
     * 
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    private String education;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column employee_inf.speciality
     * 
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    private String speciality;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column employee_inf.hobby
     * 
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    private String hobby;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column employee_inf.remark
     * 
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column employee_inf.create_date
     * 
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column employee_inf.id
     * 
     * @return the value of employee_inf.id
     * 
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column employee_inf.id
     * 
     * @param id
     *            the value for employee_inf.id
     * 
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * dept.<br/>
     * 
     * @return the dept <br/>
     * 
     */
    public Dept getDept() {
        return dept;
    }

    /**
     * dept.<br/>
     * 
     * @param dept
     *            the dept to set <br/>
     * 
     */
    public void setDept(Dept dept) {
        this.dept = dept;
    }

    /**
     * job.<br/>
     * 
     * @return the job <br/>
     * 
     */
    public Job getJob() {
        return job;
    }

    /**
     * job.<br/>
     * 
     * @param job
     *            the job to set <br/>
     * 
     */
    public void setJob(Job job) {
        this.job = job;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column employee_inf.NAME
     * 
     * @return the value of employee_inf.NAME
     * 
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column employee_inf.NAME
     * 
     * @param name
     *            the value for employee_inf.NAME
     * 
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column employee_inf.card_id
     * 
     * @return the value of employee_inf.card_id
     * 
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    public String getCardId() {
        return cardId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column employee_inf.card_id
     * 
     * @param cardId
     *            the value for employee_inf.card_id
     * 
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    public void setCardId(String cardId) {
        this.cardId = cardId == null ? null : cardId.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column employee_inf.address
     * 
     * @return the value of employee_inf.address
     * 
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column employee_inf.address
     * 
     * @param address
     *            the value for employee_inf.address
     * 
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column employee_inf.post_code
     * 
     * @return the value of employee_inf.post_code
     * 
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    public String getPostCode() {
        return postCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column employee_inf.post_code
     * 
     * @param postCode
     *            the value for employee_inf.post_code
     * 
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    public void setPostCode(String postCode) {
        this.postCode = postCode == null ? null : postCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column employee_inf.tel
     * 
     * @return the value of employee_inf.tel
     * 
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column employee_inf.tel
     * 
     * @param tel
     *            the value for employee_inf.tel
     * 
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column employee_inf.phone
     * 
     * @return the value of employee_inf.phone
     * 
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column employee_inf.phone
     * 
     * @param phone
     *            the value for employee_inf.phone
     * 
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column employee_inf.qq_num
     * 
     * @return the value of employee_inf.qq_num
     * 
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    public String getQqNum() {
        return qqNum;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column employee_inf.qq_num
     * 
     * @param qqNum
     *            the value for employee_inf.qq_num
     * 
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    public void setQqNum(String qqNum) {
        this.qqNum = qqNum == null ? null : qqNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column employee_inf.email
     * 
     * @return the value of employee_inf.email
     * 
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column employee_inf.email
     * 
     * @param email
     *            the value for employee_inf.email
     * 
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column employee_inf.sex
     * 
     * @return the value of employee_inf.sex
     * 
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column employee_inf.sex
     * 
     * @param sex
     *            the value for employee_inf.sex
     * 
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column employee_inf.party
     * 
     * @return the value of employee_inf.party
     * 
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    public String getParty() {
        return party;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column employee_inf.party
     * 
     * @param party
     *            the value for employee_inf.party
     * 
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    public void setParty(String party) {
        this.party = party == null ? null : party.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column employee_inf.birthday
     * 
     * @return the value of employee_inf.birthday
     * 
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column employee_inf.birthday
     * 
     * @param birthday
     *            the value for employee_inf.birthday
     * 
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column employee_inf.race
     * 
     * @return the value of employee_inf.race
     * 
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    public String getRace() {
        return race;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column employee_inf.race
     * 
     * @param race
     *            the value for employee_inf.race
     * 
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    public void setRace(String race) {
        this.race = race == null ? null : race.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column employee_inf.education
     * 
     * @return the value of employee_inf.education
     * 
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column employee_inf.education
     * 
     * @param education
     *            the value for employee_inf.education
     * 
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    public void setEducation(String education) {
        this.education = education == null ? null : education.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column employee_inf.speciality
     * 
     * @return the value of employee_inf.speciality
     * 
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    public String getSpeciality() {
        return speciality;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column employee_inf.speciality
     * 
     * @param speciality
     *            the value for employee_inf.speciality
     * 
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    public void setSpeciality(String speciality) {
        this.speciality = speciality == null ? null : speciality.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column employee_inf.hobby
     * 
     * @return the value of employee_inf.hobby
     * 
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    public String getHobby() {
        return hobby;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column employee_inf.hobby
     * 
     * @param hobby
     *            the value for employee_inf.hobby
     * 
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    public void setHobby(String hobby) {
        this.hobby = hobby == null ? null : hobby.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column employee_inf.remark
     * 
     * @return the value of employee_inf.remark
     * 
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column employee_inf.remark
     * 
     * @param remark
     *            the value for employee_inf.remark
     * 
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column employee_inf.create_date
     * 
     * @return the value of employee_inf.create_date
     * 
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column employee_inf.create_date
     * 
     * @param createDate
     *            the value for employee_inf.create_date
     * 
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}