package org.tton.hrm.domain;

import java.io.Serializable;

 /**
 * ClassName: Job <br/>
 * Description: TODO <br/>
 * Date: 2018年3月23日 下午10:47:32 <br/>
 * <br/>
 * 
 * @author hanyouchuan(邮箱)
 * 
 * 修改记录
 * @version 产品版本信息 yyyy-mm-dd 姓名(邮箱) 修改信息<br/>
 * 
 */
public class Job implements Serializable{
 
    private static final long serialVersionUID = 2366940707270432794L;
    
    public Job(){
        super();
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_inf.id
     *
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_inf.NAME
     *
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_inf.remark
     *
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_inf.id
     *
     * @return the value of job_inf.id
     *
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_inf.id
     *
     * @param id the value for job_inf.id
     *
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_inf.NAME
     *
     * @return the value of job_inf.NAME
     *
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_inf.NAME
     *
     * @param name the value for job_inf.NAME
     *
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_inf.remark
     *
     * @return the value of job_inf.remark
     *
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_inf.remark
     *
     * @param remark the value for job_inf.remark
     *
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
    
    @Override
    public String toString() {
        return "Job [id=" + id + ", name=" + name + ", remark=" + remark + "]";
    }
    
}