package org.tton.hrm.domain;

import java.io.Serializable;
import java.util.Date;

 /**
 * ClassName: Notice <br/>
 * Description: TODO <br/>
 * Date: 2018年3月23日 下午10:47:39 <br/>
 * <br/>
 * 
 * @author hanyouchuan(邮箱)
 * 
 * 修改记录
 * @version 产品版本信息 yyyy-mm-dd 姓名(邮箱) 修改信息<br/>
 * 
 */
public class Notice implements Serializable{
    /**
     * serialVersionUID:
     * 
     */
    private static final long serialVersionUID = -7930480006903263831L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_inf.id
     *
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_inf.title
     *
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_inf.create_date
     *
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_inf.user_id
     *
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    private User user;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_inf.content
     *
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_inf.id
     *
     * @return the value of notice_inf.id
     *
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_inf.id
     *
     * @param id the value for notice_inf.id
     *
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_inf.title
     *
     * @return the value of notice_inf.title
     *
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_inf.title
     *
     * @param title the value for notice_inf.title
     *
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_inf.create_date
     *
     * @return the value of notice_inf.create_date
     *
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_inf.create_date
     *
     * @param createDate the value for notice_inf.create_date
     *
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }


    /**
     * user.<br/>
     *
     * @return  the user <br/>
     * 
     */
    public User getUser() {
        return user;
    }

    /**
     * user.<br/>
     *
     * @param   user    the user to set <br/>
     * 
     */
    public void setUser(User user) {
        this.user = user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_inf.content
     *
     * @return the value of notice_inf.content
     *
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_inf.content
     *
     * @param content the value for notice_inf.content
     *
     * @mbggenerated Wed Jan 17 19:35:48 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}