package org.tton.hrm.domain;

import java.io.Serializable;
import java.util.Date;

 /**
 * ClassName: OvertimeProject <br/>
 * Description: TODO <br/>
 * Date: 2018年3月23日 下午10:47:44 <br/>
 * <br/>
 * 
 * @author hanyouchuan(邮箱)
 * 
 * 修改记录
 * @version 产品版本信息 yyyy-mm-dd 姓名(邮箱) 修改信息<br/>
 * 
 */
public class OvertimeProject implements Serializable {
    /**
     * serialVersionUID:TODO(描述这个变量用途).
     * 
     */
    private static final long serialVersionUID = -7068673299119383323L;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column overtime_project.id
     * 
     * @mbggenerated Wed Jan 24 10:38:55 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column overtime_project.title
     * 
     * @mbggenerated Wed Jan 24 10:38:55 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column overtime_project.remark
     * 
     * @mbggenerated Wed Jan 24 10:38:55 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column overtime_project.create_date
     * 
     * @mbggenerated Wed Jan 24 10:38:55 CST 2018
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column overtime_project.user_id
     * 
     * @mbggenerated Wed Jan 24 10:38:55 CST 2018
     */
    private User user;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column overtime_project.id
     * 
     * @return the value of overtime_project.id
     * 
     * @mbggenerated Wed Jan 24 10:38:55 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column overtime_project.id
     * 
     * @param id
     *            the value for overtime_project.id
     * 
     * @mbggenerated Wed Jan 24 10:38:55 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column overtime_project.title
     * 
     * @return the value of overtime_project.title
     * 
     * @mbggenerated Wed Jan 24 10:38:55 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column overtime_project.title
     * 
     * @param title
     *            the value for overtime_project.title
     * 
     * @mbggenerated Wed Jan 24 10:38:55 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column overtime_project.remark
     * 
     * @return the value of overtime_project.remark
     * 
     * @mbggenerated Wed Jan 24 10:38:55 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column overtime_project.remark
     * 
     * @param remark
     *            the value for overtime_project.remark
     * 
     * @mbggenerated Wed Jan 24 10:38:55 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column overtime_project.create_date
     * 
     * @return the value of overtime_project.create_date
     * 
     * @mbggenerated Wed Jan 24 10:38:55 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column overtime_project.create_date
     * 
     * @param createDate
     *            the value for overtime_project.create_date
     * 
     * @mbggenerated Wed Jan 24 10:38:55 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * user.<br/>
     * 
     * @return the user <br/>
     * 
     */
    public User getUser() {
        return user;
    }

    /**
     * user.<br/>
     * 
     */
    public void setUser(User user) {
        this.user = user;
    }

}