package org.tton.hrm.domain;

import java.io.Serializable;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

 /**
 * ClassName: OvertimeRecord <br/>
 * Description: TODO <br/>
 * Date: 2018年3月23日 下午10:47:53 <br/>
 * <br/>
 * 
 * @author hanyouchuan(邮箱)
 * 
 * 修改记录
 * @version 产品版本信息 yyyy-mm-dd 姓名(邮箱) 修改信息<br/>
 * 
 */
public class OvertimeRecord implements Serializable {
    /**
     * serialVersionUID:TODO(描述这个变量用途).
     * 
     */
    private static final long serialVersionUID = -702073920169257020L;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column overtime_record.id
     * 
     * @mbggenerated Wed Jan 24 10:38:55 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column overtime_record.work_id
     * 
     * @mbggenerated Wed Jan 24 10:38:55 CST 2018
     */
    private Integer workId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column overtime_record.NAME
     * 
     * @mbggenerated Wed Jan 24 10:38:55 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column overtime_record.start_date
     * 
     * @mbggenerated Wed Jan 24 10:38:55 CST 2018
     */
    // @DateTimeFormat(pattern="yyyy-MM-dd")
    private String startDate;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column overtime_record.end_date
     * 
     * @mbggenerated Wed Jan 24 10:38:55 CST 2018
     */
   // @DateTimeFormat(pattern="yyyy-MM-dd")  
    private String endDate;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column overtime_record.start_time
     * 
     * @mbggenerated Wed Jan 24 10:38:55 CST 2018
     */
    //@DateTimeFormat(pattern="HH:mm:ss") 
    private String startTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column overtime_record.end_time
     * 
     * @mbggenerated Wed Jan 24 10:38:55 CST 2018
     */
    //@DateTimeFormat(pattern="HH:mm:ss") 
    private String endTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column overtime_record.overtime_lenth
     * 
     * @mbggenerated Wed Jan 24 10:38:55 CST 2018
     */
    private Integer overtimeLenth;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column overtime_record.overtime_project_id
     * 
     * @mbggenerated Wed Jan 24 10:38:55 CST 2018
     */
    private OvertimeProject overtimeProject;
    
    /**
     * 加班事由
     */
    private String overtimeReason;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column overtime_record.id
     * 
     * @return the value of overtime_record.id
     * 
     * @mbggenerated Wed Jan 24 10:38:55 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column overtime_record.id
     * 
     * @param id
     *            the value for overtime_record.id
     * 
     * @mbggenerated Wed Jan 24 10:38:55 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column overtime_record.work_id
     * 
     * @return the value of overtime_record.work_id
     * 
     * @mbggenerated Wed Jan 24 10:38:55 CST 2018
     */
    public Integer getWorkId() {
        return workId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column overtime_record.work_id
     * 
     * @param workId
     *            the value for overtime_record.work_id
     * 
     * @mbggenerated Wed Jan 24 10:38:55 CST 2018
     */
    public void setWorkId(Integer workId) {
        this.workId = workId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column overtime_record.NAME
     * 
     * @return the value of overtime_record.NAME
     * 
     * @mbggenerated Wed Jan 24 10:38:55 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column overtime_record.NAME
     * 
     * @param name
     *            the value for overtime_record.NAME
     * 
     * @mbggenerated Wed Jan 24 10:38:55 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column overtime_record.start_date
     * 
     * @return the value of overtime_record.start_date
     * 
     * @mbggenerated Wed Jan 24 10:38:55 CST 2018
     */
    public String getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column overtime_record.start_date
     * 
     * @param startDate
     *            the value for overtime_record.start_date
     * 
     * @mbggenerated Wed Jan 24 10:38:55 CST 2018
     */
    public void setStartDate(String startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column overtime_record.end_date
     * 
     * @return the value of overtime_record.end_date
     * 
     * @mbggenerated Wed Jan 24 10:38:55 CST 2018
     */
    public String getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column overtime_record.end_date
     * 
     * @param endDate
     *            the value for overtime_record.end_date
     * 
     * @mbggenerated Wed Jan 24 10:38:55 CST 2018
     */
    public void setEndDate(String endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column overtime_record.start_time
     * 
     * @return the value of overtime_record.start_time
     * 
     * @mbggenerated Wed Jan 24 10:38:55 CST 2018
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column overtime_record.start_time
     * 
     * @param startTime
     *            the value for overtime_record.start_time
     * 
     * @mbggenerated Wed Jan 24 10:38:55 CST 2018
     */
    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column overtime_record.end_time
     * 
     * @return the value of overtime_record.end_time
     * 
     * @mbggenerated Wed Jan 24 10:38:55 CST 2018
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column overtime_record.end_time
     * 
     * @param endTime
     *            the value for overtime_record.end_time
     * 
     * @mbggenerated Wed Jan 24 10:38:55 CST 2018
     */
    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column overtime_record.overtime_lenth
     * 
     * @return the value of overtime_record.overtime_lenth
     * 
     * @mbggenerated Wed Jan 24 10:38:55 CST 2018
     */
    public Integer getOvertimeLenth() {
        return overtimeLenth;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column overtime_record.overtime_lenth
     * 
     * @param overtimeLenth
     *            the value for overtime_record.overtime_lenth
     * 
     * @mbggenerated Wed Jan 24 10:38:55 CST 2018
     */
    public void setOvertimeLenth(Integer overtimeLenth) {
        this.overtimeLenth = overtimeLenth;
    }

    /**
     * overtimeProject.<br/>
     * 
     * @return the overtimeProject <br/>
     * 
     */
    public OvertimeProject getOvertimeProject() {
        return overtimeProject;
    }

    /**
     * overtimeProject.<br/>
     * 
     * @param overtimeProject
     *            the overtimeProject to set <br/>
     * 
     */
    public void setOvertimeProject(OvertimeProject overtimeProject) {
        this.overtimeProject = overtimeProject;
    }

    /**
     * overtimeReason.<br/>
     *
     * @return  the overtimeReason <br/>
     * 
     */
    public String getOvertimeReason() {
        return overtimeReason;
    }

    /**
     * overtimeReason.<br/>
     *
     * @param   overtimeReason    the overtimeReason to set <br/>
     * 
     */
    public void setOvertimeReason(String overtimeReason) {
        this.overtimeReason = overtimeReason;
    }
    
    
}
